logging:
  mode: offline
  project: # Adapt
  notes: CellViTSAMStarDist-SAM-H-Fold-1
  log_comment: CellViTSAMStarDist-SAM-H-Fold-1
  tags:
  - "Fold-1"
  - "CellViTSAMStarDist"
  - "SAM-H"
  wandb_dir: /homes/fhoerst/histo-projects/CellViT/debug
  log_dir: /homes/fhoerst/histo-projects/CellViT/debug
  level: Debug
  group: CellViTSAMStarDist-SAM-H

random_seed: 19

gpu: 0

data:
  dataset: PanNuke
  dataset_path: /projects/datashare/tio/histopathology/public-datasets/PanNuke/digitalhistologyhub
  train_folds:
  - 0
  val_folds:
  - 1
  test_folds:
  - 2
  num_nuclei_classes: 6
  num_tissue_classes: 19

# model:
#   backbone: SAM-H
#   pretrained_encoder: /homes/fhoerst/histo-projects/CellViT/models/pretrained/SAM/sam_vit_h.pth # Adapt to your path

model:
  backbone: ViT256
  pretrained_encoder: /homes/fhoerst/histo-projects/CellViT/models/pretrained/ViT-256/vit256_small_dino.pth # Adapt to your path


training:
  drop_rate: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 16
  epochs: 130
  optimizer: AdamW
  early_stopping_patience: 130
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.85
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0003
    weight_decay: 0.0001
  unfreeze_epoch: 25
  sampling_gamma: 0.85
  sampling_strategy: cell+tissue

transformations:
  randomrotate90:
    p: 0.5
  horizontalflip:
    p: 0.5
  verticalflip:
    p: 0.5
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5

eval_checkpoint: "latest_checkpoint.pth"
