logging:
  mode: online
  project: CONIC
  notes: CellViT-SAM
  log_comment: CellViT-SAM-All-Folds
  tags:
  - SAM
  wandb_dir: /homes/fhoerst/histo-projects/CellViT/results/wandb
  log_dir: /homes/fhoerst/histo-projects/CellViT/results/Lizzard/SAM/2023-08-30T132808_CellViT-SAM-All-Folds
  level: Debug
  group: SAM
  run_id: f3iqv9gg
  wandb_file: f3iqv9gg
random_seed: 19
gpu: 0
data:
  dataset: Lizzard
  dataset_path: /projects/datashare/tio/histopathology/public-datasets/CONIC/digitalhistologyhub
  train_folds:
  - 1
  - 2
  - 3
  val_split: 0.1
  num_nuclei_classes: 7
  magnification: 20
model:
  backbone: SAM-H
  pretrained_encoder: ./models/pretrained/SAM/sam_vit_h.pth
  shared_skip_connections: true
loss:
  nuclei_binary_map:
    focaltverskyloss:
      loss_fn: FocalTverskyLoss
      weight: 1
    dice:
      loss_fn: dice_loss
      weight: 1
  hv_map:
    mse:
      loss_fn: mse_loss_maps
      weight: 2.5
    msge:
      loss_fn: msge_loss_maps
      weight: 8
  nuclei_type_map:
    bce:
      loss_fn: xentropy_loss
      weight: 0.5
    dice:
      loss_fn: dice_loss
      weight: 0.2
    mcfocaltverskyloss:
      loss_fn: MCFocalTverskyLoss
      weight: 0.5
      args:
        num_classes: 7
training:
  drop_rate: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 16
  epochs: 125
  optimizer: AdamW
  early_stopping_patience: 125
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.99
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0005
    weight_decay: 0.0001
  unfreeze_epoch: 10
  sampling_strategy: cell
  sampling_gamma: 0.85
  mixed_precision: true
transformations:
  randomrotate90:
    p: 0.5
  horizontalflip:
    p: 0.5
  verticalflip:
    p: 0.5
  downscale:
    p: 0.15
    scale: 0.5
  blur:
    p: 0.2
    blur_limit: 10
  gaussnoise:
    p: 0.25
    var_limit: 50
  colorjitter:
    p: 0.2
    scale_setting: 0.25
    scale_color: 0.1
  superpixels:
    p: 0.1
  zoomblur:
    p: 0.1
  elastictransform:
    p: 0.2
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
eval_checkpoint: latest_checkpoint.pth
run_sweep: false
agent: null
dataset_config:
  tissue_types:
    Colon: 0
  nuclei_types:
    Background: 0
    Neutrophil: 1
    Epithelial: 2
    Lymphocyte: 3
    Plasma: 4
    Eosinophil: 5
    Connective: 6
